apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: prometheus
spec:
  provisionerClassName: core-rukpak-io-plain
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      provisionerClassName: core-rukpak-io-registry
      source:
        type: image
        image:
          ref: quay.io/operatorhubio/prometheus:v0.47.0--20220325T220130
